<section class="row">
  <div class="col-md-4 offset-4 mt-5">
    <h1>Login</h1>

    <hr>

    <form action="" method="post">
      <input class="form-control mb-3" type="email" name="email" placeholder="Email">
      <input class="form-control mb-3" type="password" name="password" placeholder="Senha">

      <div class="d-grid">
        <button class="btn btn-primary">ENTRAR</button>
      </div>
    </form>
  </div>
</section>
