<h2>Categorias</h2>
<hr>

<div class="text-end mt-2 mb-3">
  <a href="/categorias/pdf" class="btn btn-light">Gerar PDF</a>
</div>

<table class="table table-hover table-striped">
    <tr class="table-dark">
        <th>#ID</th>
        <th>Nome</th>
        <th>Descrição</th>
    </tr>

    <tbody class="table-light">
      <?php
        foreach ($data['categories'] as $id => $category) {

          echo "
            <tr>
              <td>{$category->getId()}</td>
              <td>{$category->getName()}</td>
              <td>{$category->getDescription()}</td>
            </tr>
          ";
        }
      ?>
    </tbody>
</table>
