<h1>Adicionar Usuário</h1>
<hr>

<section class="row mt-5">
  <div class="col">
    IMAGEM AQUI
  </div>

  <div class="col">
    <form action="" method="post">
      <label for="user-name">Nome</label>
      <input id="user-name" type="text" name="user-name" class="form-control mb-3">

      <label for="user-email">Email</label>
      <input id="user-email" type="email" name="user-email" class="form-control mb-3">

      <label for="user-password">Senha</label>
      <input id="user-password" type="password" name="user-password" class="form-control mb-3">

      <div class="d-grid">
        <button class="btn btn-primary">Enviar</button>
      </div>
    </form>
  </div>
</section>
