<h1>Listar usuários</h1>
<hr>

<div class="text-end mb-3">
  <a class="btn btn-light" href="/usuarios/novo">Novo Usuário</a>
</div>

<table class="table table-hover table-striped">
  <thead class="text-white">
    <tr>
      <th>#ID</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Senha</th>
      <th>Status</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody class="table-light">
    <?php
      foreach($data as $user) {
        echo "
          <tr>
            <td>{$user->getId()}</td>
            <td>{$user->getName()}</td>
            <td>{$user->getEmail()}</td>
            <td>{$user->getPassword()}</td>
            <td>{$user->getStatus()}</td>
            <td>---</td>
          </tr>
        ";
      }
    ?>
  </tbody>
</table>
